"""Validation of the Element C panel (src/c_panel.py) on a few months, before the PREREG freeze.
Checks only the construction: residual sanity (betas, out-of-sample fit), coverage of every column, the distribution of
the outcome, its relation to industry and to its own history. It deliberately computes NO association between the
outcome and text similarity (that is b-bar, PREREG's primary statistic, computed only after the freeze).
Writes analysis/output/c_panel/README.md (aggregates only). Run: python analysis/c_panel_check.py"""
import sys, os, time
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; sys.path.insert(0, str(ROOT / 'src'))
import numpy as np, pandas as pd
import formation as F, c_panel as C

MONTHS = ['2014-07', '2020-01', '2025-07']
OUT = ROOT / 'analysis' / 'output' / 'c_panel'; OUT.mkdir(parents=True, exist_ok=True)

def md(d):
    return '\n'.join(['| ' + ' | '.join(map(str, d.columns)) + ' |', '|' + '---|' * d.shape[1]] +
                     ['| ' + ' | '.join(str(v) for v in r) + ' |' for r in d.itertuples(index=False)])

if __name__ == '__main__':
    t0 = time.time(); E, dates, cols, B = C._load()
    # 1. residual panel sanity by year: EW mean market beta, median out-of-sample R^2 (1 - var(e)/var(x) within month)
    dw, cw, R = F.daily_wide(); ff = F.factors_daily().reindex(dw); X = R - ff.RF.to_numpy(np.float32)[:, None]
    rows = []
    for y in range(2011, 2027):
        b = B[B.ym.dt.year == y]
        k0, k1 = dates.searchsorted(pd.Timestamp(f'{y}-01-01')), dates.searchsorted(pd.Timestamp(f'{y + 1}-01-01'))
        e, x = E[k0:k1], X[k0:k1]; ok = np.isfinite(e) & np.isfinite(x); n = ok.sum(0); keep = n >= 120
        ve = np.nanvar(np.where(ok, e, np.nan), 0)[keep]; vx = np.nanvar(np.where(ok, x, np.nan), 0)[keep]
        rows.append({'year': y, 'stock-months': len(b), 'mean beta_Mkt': round(b.b_Mkt_RF.mean(), 3), 'median beta_Mkt': round(b.b_Mkt_RF.median(), 3),
                     'median OOS R2': round(float(np.median(1 - ve / vx)), 3), 'mean resid (bp/day)': round(float(np.nanmean(e) * 1e4), 2)})
    res = pd.DataFrame(rows)
    # 2. pair panel on a few months
    out = []
    for m in MONTHS:
        s = time.time(); f, P = C.c_month(m); rho = np.tanh(P.z)
        same = P.same_sic3 == 1
        out.append({'month': m, 'firms': len(f), 'with beta': int(f.has_beta.sum()), 'pairs': len(P),
                    'z': f'{P.z.notna().mean():.1%}', 'z_lag': f'{P.z_lag.notna().mean():.1%}', 'db': f'{P.db_Mkt_RF.notna().mean():.1%}',
                    'd_illiq': f'{P.d_illiq.notna().mean():.1%}', 'd_bm': f'{P.d_bm.notna().mean():.1%}', 's_dense': f'{P.s_dense.notna().mean():.1%}',
                    'all cols': f'{P.drop(columns=["i", "j"]).notna().all(1).mean():.1%}',
                    'mean rho': round(float(rho.mean()), 3), 'SD rho': round(float(rho.std()), 3), 'mean z': round(float(P.z.mean()), 3),
                    'mean z same SIC-3': round(float(P.z[same].mean()), 3), 'mean z other': round(float(P.z[~same].mean()), 3),
                    'corr(z, z_lag)': round(float(P.z.corr(P.z_lag)), 3), 'mean z_lag': round(float(P.z_lag.mean()), 3), 'secs': round(time.time() - s)})
        print(out[-1], flush=True)
    pan = pd.DataFrame(out)
    txt = ['# Element C panel: construction checks', '',
           'Generated by `analysis/c_panel_check.py`. No statistic relating the outcome to text similarity is computed '
           'before the PREREG freeze (b̄ is primary).', '',
           '## FF6 residual panel (out-of-sample: month m residuals use betas from the 252 trading days before m)', '', md(res), '',
           'OOS R² = 1 − var(residual)/var(excess return) within the month, per stock, median over stocks with ≥ 120 days in the year.', '',
           '## Pair panel on three formation months (top 1,000 firms, 499,500 pairs)', '', md(pan.drop(columns='secs')), '',
           'Coverage columns: share of pairs with a finite value. z = atanh(ρ) of within-month residual correlation (≥ 15 common days); '
           'z_lag over months t−12..t−1 (≥ 126 common days); db = |Δβ_Mkt|.', '', f'Runtime {time.time() - t0:.0f} s.']
    (OUT / 'README.md').write_text('\n'.join(txt) + '\n'); print(res.to_string(index=False)); print(pan.to_string(index=False))
