"""Coverage count for the SPEC §3 delisting imputation in Element E (PREREG D14 item 1). A COUNT only: which E
firm-months have their month-t dependent return imputed. Uses universe membership, price at t-1 and the text network
(no return enters the E sample definition), and never reads a test-period return value.
E firm-month (t, i): i in formation.universe_at(t), |price| >= $1 at t-1, >= 1 text peer (BoW null-corrected at SIC-3
density). Imputed: t is the DelistingDt month of a performance-related (GDR) delisting with a missing DelRet.
Writes analysis/output/e_delisting/README.md. Run through the runner: python src/runner.py run E_delisting_coverage"""
import sys, time
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; sys.path.insert(0, str(ROOT / 'src'))
import numpy as np, pandas as pd
import formation as F, networks as N, delisting as D

FIRST, LAST, DEV_LAST = pd.Period('2012-07', 'M'), pd.Period('2026-06', 'M'), pd.Period('2018-11', 'M')
OUT = ROOT / 'analysis' / 'output' / 'e_delisting'; OUT.mkdir(parents=True, exist_ok=True)

def in_e_sample(t, permnos):
    """For each permno: in E's sample at t? (universe with text, price >= 1 at t-1, >= 1 text peer)."""
    u = F.universe_at(t).reset_index(drop=True)
    prev = F.monthly()[F.monthly().ym == t - 1].set_index('permno')
    prc = prev.mthprc.abs().reindex(u.permno).to_numpy()
    S = N.bow_sim(t.to_timestamp(), u.accession.to_numpy()); A = N.peers(S, N.density(u))
    ok = pd.Series((prc >= 1) & (A.sum(1) > 0), index=u.permno.to_numpy())
    return {p: bool(ok.get(p, False)) for p in permnos}, int(((prc >= 1) & (A.sum(1) > 0)).sum())

if __name__ == '__main__':
    t0 = time.time(); d = D.load()
    d = d[(d.ym >= FIRST) & (d.ym <= LAST) & d.delret_missing]
    rows = []
    for t, g in d.groupby('ym'):
        flags, _ = in_e_sample(t, g.permno.tolist())
        for r in g.itertuples():
            rows.append({'t': t, 'permno': r.permno, 'performance': r.performance, 'action': r.delactiontype, 'reason': r.delreasontype,
                         'exch': r.primaryexch, 'in_E': flags[r.permno]})
    R = pd.DataFrame(rows); R['period'] = np.where(R.t <= DEV_LAST, 'dev (Jul 2012 - Nov 2018)', 'test (Dec 2018 - Jun 2026)')
    imp = R[R.performance & R.in_E]; left = R[~R.performance & R.in_E]
    tab = pd.crosstab(imp.period, imp.exch.where(imp.exch.isin(['N', 'A', 'Q']), 'other')).assign(total=lambda x: x.sum(1))
    md = lambda df: '\n'.join(['| | ' + ' | '.join(map(str, df.columns)) + ' |', '|---|' + '---|' * df.shape[1]] +
                              [f'| {i} | ' + ' | '.join(str(v) for v in r) + ' |' for i, r in zip(df.index, df.itertuples(index=False))])
    txt = ['# E delisting imputation: coverage (count only)', '', 'Generated by `analysis/e_delisting_coverage.py` (registered spec `E_delisting_coverage`, diagnostic).', '',
           f'Delistings with a missing DelRet, DelistingDt Jul 2012 – Jun 2026: {len(R)} (performance-related GDR {int(R.performance.sum())}; other {int((~R.performance).sum())}).',
           f'Of these, in E\'s sample in their delisting month: **{len(imp)} performance-related (imputed)**, {len(left)} other (left as CRSP has them).', '',
           '## Imputed E firm-months by period and exchange at delisting', '', md(tab), '',
           'N/A: δ = −30%; Q: δ = −55%; "other" uses the firm\'s CRSP monthly exchange (PREREG D14 item 1, SPEC §3).', '',
           '## Reasons (imputed)', '', md(imp.reason.value_counts().to_frame('firm-months')), '',
           f'Runtime {time.time() - t0:.0f} s.']
    (OUT / 'README.md').write_text('\n'.join(txt) + '\n'); print('\n'.join(txt))
