"""Element E on the DEVELOPMENT period only (Jul 2012 - Nov 2018; PREREG draft: the test period Dec 2018 - Jun 2026 is
untouched until the freeze). Before anything runs, the monthly CRSP panel held by src/formation.py is replaced by its
rows up to 2018-11 and the factor file is cut at 2018-11, so no test-period return can enter any signal, control or
dependent variable; the script asserts it.
Specification (PREREG draft, Element E): src/e_signals.signals_at(t); dependent = month-t return minus the FF risk-free
rate; right-hand side winsorised at 1/99 and z-scored each month; Fama-MacBeth via tfs_stats.regression.fama_macbeth
with NW(L = nw_lags_rule(77) = 3) x T/(T-1); NW(2) for comparability with Hoberg-Phillips; EWC via tfs_stats.ewc on the
slope series (nu = ewc_nu_rule(77) = 7). Writes analysis/output/e_dev/README.md (aggregates only)."""
import sys, time
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; sys.path.insert(0, str(ROOT / 'src')); sys.path.insert(0, str(ROOT))
import numpy as np, pandas as pd
import formation as F
from paths import PROCESSED
from tfs_stats.regression import fama_macbeth, fm_inference, ewc, nw_lags_rule, ewc_nu_rule

DEV_FIRST, DEV_LAST = pd.Period('2012-07', 'M'), pd.Period('2018-11', 'M')
OUT = ROOT / 'analysis' / 'output' / 'e_dev'; OUT.mkdir(parents=True, exist_ok=True)
RHS = ['peermom', 'log_me', 'log_bm', 'r_1', 'r12_2', 'indmom', 'sic3mom', 'tnicmom']

def zwin(s):
    lo, hi = s.quantile([0.01, 0.99]); s = s.clip(lo, hi); return (s - s.mean()) / s.std()

if __name__ == '__main__':
    t0 = time.time()
    full = pd.read_parquet(PROCESSED / 'crsp_monthly.parquet')
    F._cache['m'] = full[full.ym <= DEV_LAST].copy(); del full                    # hold back the test period
    assert F.monthly().ym.max() == DEV_LAST
    import e_signals as E
    ffm = pd.read_parquet(PROCESSED / 'ff_monthly.parquet'); ffm = ffm[ffm.ym <= DEV_LAST].set_index('ym')
    rows = []
    for t in pd.period_range(DEV_FIRST, DEV_LAST, freq='M'):
        u = E.signals_at(t)
        y = F.monthly()[F.monthly().ym == t].set_index('permno').ret.reindex(u.permno).to_numpy() - ffm.RF.loc[t]
        u['exret'] = y; rows.append(u)
        if t.month in (1, 7): print(t, len(u), f'{time.time() - t0:.0f}s', flush=True)
    P = pd.concat(rows, ignore_index=True)
    assert P.t.max() <= DEV_LAST
    d = P.dropna(subset=['exret'] + RHS).copy()
    for c in RHS: d[c] = d.groupby('t')[c].transform(zwin)
    T = d.t.nunique(); L = nw_lags_rule(T); nu = ewc_nu_rule(T)
    res = fama_macbeth(d.exret.to_numpy(), d[RHS].to_numpy(), d.t.astype(str).to_numpy(), nw_lags=L)
    nw2 = fm_inference(res['lambdas'], 2); ew = ewc(res['lambdas'], nu)
    uni = fama_macbeth(d.exret.to_numpy(), d[['peermom']].to_numpy(), d.t.astype(str).to_numpy(), nw_lags=L)
    names = ['const'] + RHS
    tab = pd.DataFrame({'coef (%/month per SD)': np.round(res['coef'] * 100, 3), f'NW({L}) t': np.round(res['tstat'], 2),
                        'NW(2) t': np.round(nw2['tstat'], 2), f'EWC({nu}) t': np.round(ew['tstat'], 2), f'EWC p (t_{nu})': np.round(ew['pvalue'], 3)}, index=names)
    cov = P[RHS + ['exret']].notna().mean().round(3)
    md = lambda df: '\n'.join(['| | ' + ' | '.join(df.columns) + ' |', '|---|' + '---|' * df.shape[1]] + [f'| {i} | ' + ' | '.join(str(v) for v in r) + ' |' for i, r in zip(df.index, df.itertuples(index=False))])
    txt = ['# Element E — development period only (Jul 2012 – Nov 2018)', '',
           f'Generated by `analysis/e_dev.py`. Test period (Dec 2018 – Jun 2026) held back: CRSP monthly truncated at {DEV_LAST} before any computation.', '',
           f'Months {T} (skipped {res["n_skipped"]}); firm-months {len(d):,} with every variable ({len(P):,} before dropping missing); '
           f'median firms per month {int(d.groupby("t").size().median())}; median text peers {int(P.n_peers.median())}, TNIC peers {int(P.n_tnic.median())}.', '',
           '## Fama–MacBeth, excess return in month t on z-scored (1/99-winsorised) characteristics', '', md(tab), '',
           f'Univariate PEERMOM (dev): {uni["coef"][1] * 100:.3f}%/month per SD, NW({L}) t = {uni["tstat"][1]:.2f}.', '',
           '## Coverage before dropping missing', '', md(cov.to_frame('share non-missing')), '',
           f'Runtime {time.time() - t0:.0f} s.']
    (OUT / 'README.md').write_text('\n'.join(txt) + '\n'); print('\n'.join(txt))
